version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "src"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
       Microsoft:
          patterns:
            - "Microsoft.*"
            - "MSTest.*"
